### ISSUE TITLE
RP2.0 V1 Beta - Overview 

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#102]
# RP2 Beta V1

This is a **WIP** mega-ticket for an overview into Rocket Pool 2.0's V1 Beta remaining issues. It is broken down into several core sections with their own defined areas and capabilities.

The aim here is to provide a relatively high level view of the progress towards the V1 Beta, identify areas that need work and track how each section currently operates. Some areas refer to repo's that aren't currently public (smart node) but will be in the future.

We welcome contributions, but if you’re new to Rocket Pool, this is the deep end, so if you want to know more first, we recommend some reading here to learn more about us and what we’re aiming for:

- [Website](https://www.rocketpool.net) – [www.rocketpool.net](https://www.rocketpool.net)
- [Mega-FAQ](https://medium.com/rocket-pool/rocket-pool-101-faq-ee683af10da9) – [medium.com/rocket-pool/rocket-pool-101-faq](https://medium.com/rocket-pool/rocket-pool-101-faq-ee683af10da9)
- [RP 2.0 Explainer](https://medium.com/rocket-pool/rocket-pool-2-0-the-next-generation-cc67ff2b65a8) - [medium.com/rocket-pool/rocket-pool-2-0-the-next-generation](https://medium.com/rocket-pool/rocket-pool-2-0-the-next-generation-cc67ff2b65a8)
- [RP 2.0 Beta UI Video WIP](https://www.rocketpool.net/vids/rp2-beta-quick-demo.mp4)

## Smart Contracts
Rocket Pools smart contracts contain several main categories which are listed below, each serve various purposes from registering a node with the Rocket Pool staking network, to staking as a regular user and more. 

### General
- [ ] Check solidity code coverage and update if required. Would be good to get > 90% across the board for the beta. https://github.com/rocket-pool/rocketpool/issues/99

### API Contracts
The Rocket Pool network has a full smart contract API for interacting with it. Our own pool uses these API endpoints and so can any 3rd party that wishes to offer staking for their users.

- **Rocket Admin**
    - [x] Add unit tests for `setGroupRocketPoolFeePercent()`

- **Minipools**
Users in Rocket Pool are paired up with node operators via minipool contracts. A minipool contracts features users with 16ETH + another 16ETH from a node operator.

  - **Delegate Contracts**
    - [x] Add a base contract that declares storage used for delegates and inherit these into each delegate to prevent declaring storage multiple times.
  
  - **Time Durations**
    - [x] Currently we use blocks for measuring time limits (minipool durations etc). This was originally done when Casper was a contract which our smart contracts could talk to directly. Might be worth revisiting if we should revert to timestamps that are unaffected by block times etc and more easily digestible by humans and work the same across testnets with different block times.

  - **Node Trusted**
    - [x] The RocketNodeAPI contract has a getTrusted method also. It appears Minipools store the trusted status of the node when they are created. Should we keep it this way or rely on using RocketNodeAPIs method to return its current status? Worth a discussion incase a node goes from 'trusted' to 'non-trusted' with minipools attached.

### Token Contracts
Rocket Pool has a staking token called rETH and also RPL which is used by the network to regulate network capacity.

- [x] Rebrand RPB to rETH across the board.

### Faucet Contracts

- [x] Testnet ETH Faucet contract. Should be stocked with testnet ETH and is able to give `x` amount of ETH away every 24hrs. We can probably use the contract from the first beta for this. The `x` amount can be just 8 ETH to start with. 

    Given that node operators should have 16 ETH for each minipool, might be a good idea to automate that somewhat, as most users will be staking and not running a node, so minipools will be required. Perhaps an extra CLI command just for the beta, where the faucet contracts checks if the account is a registered node, if it is, it sends it 16 ETH. This can be accessed every 4 hrs.

- [x] Testnet RPL Faucet contract. We can deploy a dummy RPL token contract that can also mint RPL every 24hrs.

## Smart Node CLI

Nodes that wish to join the Rocket Pool network can do so at anytime. They install our smart node package which contains a CLI and Daemon setup to allow connecting and interacting with the Rocket Pool network. They can stake their own ether for free in the network and earn extra returns by having Rocket Pool users assigned to their node.

### Installation

- [x] Create an installer for the smart node CLI package. 
  - [x] Install all required dependencies.
  - [x] Install the CLI + daemons and configure them to always run.
  - [x] Give the user the option to select which network to use (In the future, we'll have RP on Goerli and mainnnet, but for the beta, we will still need network selection but with just a single choice... either RP Testnet or Goerli testnet depending on what we go with).
  - [x] Give the user the option to select a ETH1 client for installation.
  - [x] Give the user the option to select a beacon chain client to install (for the beta, if we use the simulator, just give them the single option 'simulator' for it. If we use prysmatic labs testnet, just give them the option to select that client) https://github.com/rocket-pool/smartnode-cli/issues/4
- [x] Verify a server restart has all processes + daemons resume as normal.

### Deposits

- [x] Add BLS account generation when reserving a deposit. https://github.com/rocket-pool/smartnode-cli/issues/8
- [x] A bug with making a deposit reservation on testnet with 15s blocktimes. https://github.com/rocket-pool/smartnode-cli/issues/9

## Preparation

Tasks and design choices that need to be made for the beta that don't fit into any of the categories above.

- [x] Write a guide on Medium on how to use the beta. Similar to RP1 Beta here https://medium.com/rocket-pool/rocket-pool-v1-beta-launch-19th-july-7c71ee758036

----------------------------------

# RP2 Beta V2

Some initial goals for the V2 Beta. Will build this out into its own ticket once V1 Beta is underway.

## Smart Contracts

- **General**
  - Staking won't actually start until a number of validators have deposits. So with the deposit durations, do we start these from the moment the users minipool becomes a validator or when 'staking' actual begins? For the minipool duration start, we could make it something like casperStartTimestamp + minipoolDuration - that would require us adding a new setting which is updated with a timestamp for when staking actually began. Or we could automate that variable somehow using node checkins to verify its happened. Minipools will also require a new status to indicate awaiting staking activation.

### API Contracts

  - **General**
    - Reorganise API contracts into more modular components eg /api/deposit/helpers.sol  /api/deposit/deposit.sol

 - **Smart Node**
    - Light client option using Infura.
    - Add prometheus metrics to the docker containers (or write a new 'stats' one) and build a UI dashboard in Grafana to show different metrics such as; Current minipools (their status, users etc), Current blocks (ETH1, Beacon chain), Node checkins, CPU usage etc.
    - Look at integrating uniswap to provide automatic RPL trades when deposits are made. Eg. When a node operator deposits 16 ETH, they may be charged 16.05 ETH where the 0.05 ETH extra is used to buy the RPL required automatically on uniswap (if the nodes RPL account isn't currently sufficient). Makes the deposit more seamless.

  - **RPIP Voting**
    - Due Beta V2.

### Nodes
  - An admin panel for node operators to see the status of their node. Current network metrics (utilisation of each duration, their minipools, users staking etc).

**Comment by moles1** [comment]
> Currently we use blocks for measuring time limits (minipool durations etc)... Might be worth revisiting if we should revert to timestamps...

- Created a separate ticket to investigate after the beta

> The RocketNodeAPI contract has a getTrusted method also. It appears Minipools store the trusted status of the node when they are created. Should we keep it this way or rely on using RocketNodeAPIs method to return its current status?

- The current implementation is necessary in order for active minipool set construction & queue processing to function correctly - a node may have both trusted and untrusted minipools at the same time, depending on its status when they were created.

> Rebrand RPB to rETH across the board

- Implemented and awaiting deployment

**Comment by moles1** [comment]
Only remaining item is a duplicate of https://github.com/rocket-pool/rocketpool/issues/99
